### ISSUE TITLE
Validation Question: How to allow only alphabet and "space"?

### ISSUE THREAD

**Issue by EricXDing** [susanBuck/dwa15-fall2017#121] opened 2017-11-01 06:15 UTC
Hi all, 

I am building the validations for my form right now. I have a textbox where the user can put in his/her name. I set the validation to: 
>   $this->validate($request, [ 'Name' => 'required|alpha'});

However, after setting this validation rule, I can only input alphabet and not 'space'. For example, I can only put "JohnSmith" and not "John Smith". 
So is there a validation rule that allow me to add 'space'?

Thanks!

**Comment by sheetaldalvi** [comment] 2017-11-01 15:23
I think you can use regular expression to include the white spaces in validation logic

 'Name' =>'required|regex:/^[\pL\s]+$/u'

I have not tested this code. You can check this implementation https://gist.github.com/waleedrehmankhan/89444347f21a549e8c18

**Comment by dianakleban** [comment] 2017-11-01 16:57
I asked this question in the issue #104 Alpha Validation. You can see explanations there.

**Comment by natethegreat418** [comment] 2017-11-01 19:03
You can also validate against those rules on the HTML form itself. Consider the input or pattern properties:
https://stackoverflow.com/questions/19619428/html5-form-validation-pattern-alphanumeric-with-spaces

**Comment by dukesnuz** [comment] 2017-11-01 19:15
@EricXDing What if you add another input field. One for first name and one for last name.

**Comment by susanBuck** [comment] 2017-11-01 19:51
Duplicate of #104

**Closed by susanBuck** 2017-11-01 19:51 UTC
