### ISSUE TITLE
how to use w3 validator behind auth

### ISSUE THREAD

**Issue by drumph33** [susanBuck/dwa15-fall2017#234] opened 2017-12-13 19:24 UTC
When I go to use the w3 validator it always gets sent to the login page because no user is logged in and the routes are auth protected.

**Comment by gabrielsanna** [comment] 2017-12-13 19:35
This is a duplicate of issue 217:

[https://github.com/susanBuck/dwa15-fall2017/issues/217](https://github.com/susanBuck/dwa15-fall2017/issues/217)

**Closed** 2017-12-13 19:50 UTC
